# Docs: https://github.com/realm/SwiftLint

# Default rules configuration
line_length:
  warning: 100
  error: 120
  ignores_comments: true

type_name:
  max_length: 60
  excluded:
    - ID

function_body_length:
  warning: 50
  error: 60

function_parameter_count:
- 6

superfluous_disable_command: 
  severity: error
void_function_in_ternary: 
  severity: error
implicit_getter: 
  severity: error
unused_setter_value: 
  severity: error
vertical_parameter_alignment:
  severity: error
computed_accessors_order:
  severity: error
closure_parameter_position:
  severity: error
unneeded_break_in_switch:
  severity: error
self_in_property_initialization:
  severity: error
operator_whitespace:
  severity: error

# Disable rules from the default enabled set.
disabled_rules:
- control_statement
- multiple_closures_with_trailing_closure
- switch_case_alignment
- identifier_name
- inclusive_language
- orphaned_doc_comment
- for_where
- nesting
- file_length
- type_body_length
- cyclomatic_complexity
- large_tuple
- private_over_fileprivate
- todo

# Opt-in rules configuration
empty_count: 
  severity: error
empty_string: 
  severity: error
implicit_return: 
  severity: error
explicit_init: 
  severity: error
redundant_nil_coalescing: 
  severity: error
redundant_type_annotation: 
  severity: error
redundant_self_in_closure:
  severity: error
unavailable_function: 
  severity: error
unused_optional_binding: 
  severity: error
multiline_arguments: 
  severity: error
  only_enforce_after_first_closure_on_first_line: true
multiline_arguments_brackets: 
  severity: error
multiline_parameters: 
  severity: error
multiline_parameters_brackets: 
  severity: error
multiline_literal_brackets: 
  severity: error
force_unwrapping: 
  severity: error
discouraged_object_literal:
  severity: error
discouraged_optional_collection:
  severity: error

opt_in_rules:
- empty_count # error
- empty_string # error
- implicit_return # error
- explicit_init # error
- redundant_nil_coalescing # error
- redundant_type_annotation # error
- redundant_self_in_closure # error
- unavailable_function # error
- unused_optional_binding # error
- multiline_arguments # error
- multiline_arguments_brackets # error
- multiline_parameters # error
- multiline_parameters_brackets # error
- multiline_literal_brackets # error
- force_unwrapping # error
- discouraged_object_literal # error
- discouraged_optional_collection # error

analyzer_rules:
  - unused_declaration
  - unused_import

warning_threshold: 50
