name: EatHub
options:
  bundleIdPrefix: com.yandex.sirius
configs:
  Debug: debug
  Release: release
settings:
  SDKROOT: iphoneos
  IPHONEOS_DEPLOYMENT_TARGET: "17.5"

targets:
  EatHub:
    type: application
    platform: iOS
    sources:
      - path: EatHub

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yandex.sirius.EatHub
      GENERATE_INFOPLIST_FILE: YES

      # ========== Настройки компиляции ==========

      CLANG_ENABLE_MODULES: YES
      CLANG_ENABLE_OBJC_ARC: YES
      CLANG_ENABLE_OBJC_WEAK: YES
      CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
      CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
      GCC_WARN_UNUSED_VARIABLE: YES

      LOCALIZATION_PREFERS_STRING_CATALOGS: YES

      MTL_FAST_MATH: YES
      ONLY_ACTIVE_ARCH: YES
      COPY_PHASE_STRIP: NO
      ENABLE_STRICT_OBJC_MSGSEND: YES

      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"

      # Указание на ассеты (одна папка)
      DEVELOPMENT_ASSET_PATHS: "EatHub/EatHub/Design/Resources"

      ENABLE_PREVIEWS: YES

      # ========== Info.plist ключи ==========

      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"

      LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"

      PRODUCT_NAME: "$(TARGET_NAME)"
      SWIFT_VERSION: "5.0"
      TARGETED_DEVICE_FAMILY: "1"

    configs:
      Debug:
        DEBUG_INFORMATION_FORMAT: dwarf
        GCC_OPTIMIZATION_LEVEL: "0"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE

      Release:
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        ENABLE_NS_ASSERTIONS: NO
        MTL_ENABLE_DEBUG_INFO: NO
